name: Deploy and Build Frontend on Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_KEY }}
        script: |
          cd /var/www/biddius || exit 1
          git pull origin main

          ls -la
          cd Auctora-Frontend
          npm install --legacy-peer-deps
          npm run build

          # Replace the content served by Nginx
          sudo rm -rf /var/www/biddius/html/*
          sudo cp -r dist/* /var/www/biddius/html/

          # (Optional) Restart FastAPI service
          sudo systemctl restart myapp.service
